import json
import os

os.makedirs(os.path.join("public", "data", "economy"), exist_ok=True)
os.makedirs(os.path.join("public", "data", "schemes"), exist_ok=True)
os.makedirs(os.path.join("public", "data", "reports"), exist_ok=True)
os.makedirs(os.path.join("public", "data", "appointments"), exist_ok=True)

# 1. MACRO ECONOMY
economy_data = {
    "title": "Master Guide to Macro-Economy & Indian Economic Concepts for Banking Mains",
    "version": "2026.09",
    "national_income": {
        "concepts": [
            {"term": "Gross Domestic Product (GDP)", "definition": "The total monetary or market value of all finished goods and services produced within a country's domestic borders in a specific time period (usually one financial year)."},
            {"term": "Gross National Product (GNP)", "definition": "GDP + Net Factor Income from Abroad (NFIA). Measures the economic output generated by permanent residents/nationals of a country anywhere in the world."},
            {"term": "Net Domestic Product (NDP)", "definition": "GDP - Depreciation (Consumption of Fixed Capital)."},
            {"term": "Net National Product (NNP) at Factor Cost", "definition": "Known as National Income (NI). NNP at Factor Cost = NNP at Market Price - Indirect Taxes + Subsidies."},
            {"term": "Gross Value Added (GVA)", "definition": "GVA measures the contribution to an economy by an individual producer, industry, or sector. GVA at Basic Prices = GVA at Factor Cost + Production Taxes - Production Subsidies. GDP at Market Price = GVA at Basic Prices + Product Taxes - Product Subsidies."},
            {"term": "Real GDP vs Nominal GDP", "definition": "Nominal GDP is calculated at current year market prices. Real GDP is adjusted for inflation and measured at base year prices (currently Base Year 2011-12). Real GDP = (Nominal GDP / GDP Deflator) * 100."},
            {"term": "GDP Deflator", "definition": "Comprehensive measure of price inflation across all goods and services produced in the domestic economy. GDP Deflator = (Nominal GDP / Real GDP) * 100."}
        ]
    },
    "inflation_metrics": [
        {
            "metric": "Consumer Price Index (CPI) - Combined",
            "published_by": "National Statistical Office (NSO), Ministry of Statistics and Programme Implementation (MoSPI)",
            "base_year": "2012 = 100",
            "release_frequency": "Monthly (around 12th of every month)",
            "basket_composition": "Food and Beverages (45.86%), Pan, tobacco and intoxicants (2.38%), Clothing and footwear (6.53%), Housing (10.07% - urban only), Fuel and light (6.84%), Miscellaneous (services, healthcare, transport, education - 28.32%)",
            "exam_significance": "RBI's Monetary Policy Committee (MPC) uses CPI-Combined as the official nominal anchor for the Flexible Inflation Target (4% +/- 2%)."
        },
        {
            "metric": "Wholesale Price Index (WPI)",
            "published_by": "Office of the Economic Adviser, Department for Promotion of Industry and Internal Trade (DPIIT), Ministry of Commerce and Industry",
            "base_year": "2011-12 = 100",
            "release_frequency": "Monthly (around 14th of every month)",
            "basket_composition": "Manufactured Products (64.23%), Primary Articles (22.62%), Fuel & Power (13.15%)",
            "exam_significance": "Measures price changes at wholesale stage. Does NOT capture services (only physical merchandise goods)."
        },
        {
            "metric": "Index of Industrial Production (IIP)",
            "published_by": "NSO, MoSPI",
            "base_year": "2011-12 = 100",
            "sectoral_weights": "Manufacturing (77.63%), Mining (14.37%), Electricity (7.99%)",
            "eight_core_industries": "Weight: 40.27% of IIP. 1. Petroleum Refinery Products (28.04% - highest), 2. Electricity (19.85%), 3. Steel (17.92%), 4. Coal (10.33%), 5. Crude Oil (8.98%), 6. Natural Gas (6.88%), 7. Cement (5.37%), 8. Fertilizers (2.63% - lowest).",
            "exam_significance": "Frequently asked in SBI/IBPS: Highest core sector weight (Refinery Products) and lowest (Fertilizers)."
        }
    ],
    "fiscal_policy_and_deficits": {
        "budget_deficits": [
            {"type": "Fiscal Deficit", "formula": "Total Expenditure - Total Receipts (excluding borrowings)", "significance": "Total borrowing requirement of the Government from all sources (domestic markets, RBI, external). Direct gauge of macroeconomic stability."},
            {"type": "Revenue Deficit", "formula": "Revenue Expenditure - Revenue Receipts", "significance": "Indicates government borrowing to finance day-to-day administrative consumption rather than capital asset creation."},
            {"type": "Primary Deficit", "formula": "Fiscal Deficit - Interest Payments", "significance": "Reflects the borrowing requirement needed for current fiscal policies, excluding past debt legacy interest obligations."},
            {"type": "Effective Revenue Deficit", "formula": "Revenue Deficit - Grants for Creation of Capital Assets", "significance": "Adjusts for central revenue transfers to states that are used to build permanent physical infrastructure."}
        ],
        "frbm_act": {
            "name": "Fiscal Responsibility and Budget Management (FRBM) Act, 2003",
            "key_amendments": "Amended post N. K. Singh Committee Report (2017)",
            "statutory_targets": "Central Government Debt-to-GDP ratio of 40%, General Government (Centre + States) Debt-to-GDP of 60%, Fiscal Deficit target of 3.0% of GDP. Includes an 'Escape Clause' of up to 0.5% during national security crisis, war, or severe economic shock."
        }
    },
    "balance_of_payments": {
        "definition": "A systematic record of all economic transactions conducted between residents of a country and the rest of the world during a specified period.",
        "accounts": [
            {
                "account": "Current Account",
                "components": "1. Merchandise Trade (Exports - Imports of goods), 2. Invisibles (Services exports like IT/BPO, Net Transfers like worker remittances, and Net Income like dividends/interest).",
                "cad": "Current Account Deficit (CAD) occurs when imports of goods, services, and transfers exceed exports. Financed by capital account surpluses or forex reserves."
            },
            {
                "account": "Capital Account",
                "components": "1. Foreign Direct Investment (FDI - long term, managerial control >10%), 2. Foreign Portfolio Investment (FPI/FII - stock market liquid shares <10%), 3. External Commercial Borrowings (ECB), 4. External Assistance (concessional bilateral/multilateral loans), 5. Banking Capital (NRI deposits like FCNR, NRE, NRO)."
            }
        ],
        "forex_components": "Foreign Currency Assets (FCA), Gold, Special Drawing Rights (SDR), and Reserve Tranche Position (RTP) in IMF. Custodian: RBI (Section 40, RBI Act 1934)."
    }
}

with open(os.path.join("public", "data", "economy", "macro-economy.json"), "w", encoding="utf-8") as f:
    json.dump(economy_data, f, indent=2, ensure_ascii=False)

# 2. GOVERNMENT SCHEMES
schemes_data = {
    "title": "Master Guide to Central Government Flagship Schemes for Banking Exams",
    "total_schemes": 20,
    "last_updated": "2026-09-13",
    "schemes": [
        {
            "name": "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
            "nodal_ministry": "Ministry of Finance (Department of Financial Services)",
            "launch_date": "28 August 2014",
            "motto": "'Mera Khata, Bhagya Vidhata'",
            "eligibility": "Any individual aged 10 years and above",
            "key_features": [
                "Zero-balance Basic Savings Bank Deposit Account (BSBDA) with no minimum balance maintenance charges",
                "Free RuPay Debit Card with inbuilt Accidental Insurance Cover of ₹2 Lakh (for accounts opened after 28.08.2018; ₹1 Lakh earlier)",
                "Overdraft (OD) facility up to ₹10,000 (no conditions for OD up to ₹2,000; upper age limit 65 years)",
                "Direct Benefit Transfer (DBT) linkage for Jan Suraksha, PM-KISAN, and LPG subsidies"
            ],
            "exam_relevance": "Top Priority. Invariably tested on OD limit (₹10,000) and RuPay accident insurance (₹2 Lakh)."
        },
        {
            "name": "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
            "nodal_ministry": "Ministry of Finance (Department of Financial Services)",
            "launch_date": "9 May 2015 (Kolkata)",
            "eligibility": "Bank / Post office account holders aged 18 to 50 years",
            "premium": "₹436 per annum (auto-debited from bank account in one installment)",
            "risk_coverage": "Life insurance cover of ₹2 Lakh in case of death due to any cause",
            "coverage_period": "1st June to 31st May of the subsequent year",
            "exam_relevance": "Very High. Premium ₹436, entry age 18-50, life cover ₹2 Lakh."
        },
        {
            "name": "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
            "nodal_ministry": "Ministry of Finance (Department of Financial Services)",
            "launch_date": "9 May 2015 (Kolkata)",
            "eligibility": "Bank / Post office account holders aged 18 to 70 years",
            "premium": "₹20 per annum (auto-debited annually)",
            "risk_coverage": "Accidental death or permanent total disability: ₹2 Lakh; Permanent partial disability: ₹1 Lakh",
            "coverage_period": "1st June to 31st May",
            "exam_relevance": "Very High. Premium ₹20, age 18-70, accidental cover ₹2 Lakh."
        },
        {
            "name": "Atal Pension Yojana (APY)",
            "nodal_ministry": "Ministry of Finance (Administered by PFRDA)",
            "launch_date": "9 May 2015",
            "eligibility": "All Indian citizens aged 18 to 40 years having a savings bank account (Income tax payers not eligible since 1 Oct 2022)",
            "minimum_contribution_period": "Minimum 20 years (contributions till age 60)",
            "guaranteed_pension": "Fixed monthly pension of ₹1,000, ₹2,000, ₹3,000, ₹4,000, or ₹5,000 after reaching age 60",
            "death_benefit": "Spouse receives same pension; on demise of both, entire accumulated pension corpus returned to nominee",
            "exam_relevance": "Very High. Age 18-40, pension slabs ₹1k-₹5k, PFRDA regulation."
        },
        {
            "name": "Pradhan Mantri MUDRA Yojana (PMMY)",
            "nodal_ministry": "Ministry of Finance (Department of Financial Services)",
            "launch_date": "8 April 2015",
            "institution": "Micro Units Development & Refinance Agency (MUDRA), subsidiary of SIDBI",
            "categories": [
                {"category": "Shishu", "loan_amount": "Loans up to ₹50,000"},
                {"category": "Kishore", "loan_amount": "Loans above ₹50,000 and up to ₹5 Lakh"},
                {"category": "Tarun", "loan_amount": "Loans above ₹5 Lakh and up to ₹10 Lakh"},
                {"category": "Tarun Plus", "loan_amount": "Loans up to ₹20 Lakh (for entrepreneurs who have successfully repaid previous Tarun loans)"}
            ],
            "collateral": "Collateral-free loans; Credit Guarantee Fund for Micro Units (CGFMU) covers defaults",
            "exam_relevance": "Extremely High. Shishu/Kishore/Tarun/Tarun Plus limits are classic bank exam questions."
        },
        {
            "name": "Stand-Up India Scheme",
            "nodal_ministry": "Ministry of Finance (Administered by SIDBI & NABARD)",
            "launch_date": "5 April 2016 (extended up to 2025/2026)",
            "objective": "Facilitate bank loans between ₹10 Lakh and ₹1 Crore to at least one SC or ST borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise in manufacturing, services, agri-allied, or trading sector.",
            "margin_money": "Up to 15% (borrower contribution)",
            "repayment": "Repayable in 7 years with maximum moratorium period of 18 months",
            "exam_relevance": "High. ₹10 Lakh to ₹1 Crore loan range, 1 SC/ST + 1 woman per branch."
        },
        {
            "name": "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
            "nodal_ministry": "Ministry of Agriculture and Farmers Welfare",
            "launch_date": "24 February 2019 (Gorakhpur, UP; effective from 1 Dec 2018)",
            "financial_benefit": "₹6,000 per year per eligible farmer family",
            "payment_mode": "Direct Benefit Transfer (DBT) in three equal 4-monthly installments of ₹2,000 each",
            "funding": "100% Central Sector Scheme fully funded by Government of India",
            "exam_relevance": "Very High. ₹6,000 annual sum, 3 installments of ₹2,000."
        },
        {
            "name": "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
            "nodal_ministry": "Ministry of Agriculture and Farmers Welfare",
            "launch_date": "18 February 2016 (effective Kharif 2016)",
            "premium_rates": [
                {"crop_type": "Kharif Food & Oilseed crops", "farmer_premium": "2.0% of Sum Insured"},
                {"crop_type": "Rabi Food & Oilseed crops", "farmer_premium": "1.5% of Sum Insured"},
                {"crop_type": "Commercial & Horticultural crops", "farmer_premium": "5.0% of Sum Insured"}
            ],
            "subsidy": "Balance actuarial premium paid equally (50:50) by Central and State Governments (90:10 for North Eastern states)",
            "technology": "Crop cutting experiments, Digi-Claim module, YES-TECH, WINDS portal",
            "exam_relevance": "Very High. Kharif 2%, Rabi 1.5%, Commercial 5% premium rates."
        },
        {
            "name": "Kisan Credit Card (KCC) Scheme",
            "nodal_agency": "NABARD / RBI / Ministry of Agriculture",
            "launch_date": "August 1998 (designed by R. V. Gupta Committee)",
            "features": [
                "Provides timely short-term credit to farmers for crop cultivation and post-harvest expenses",
                "Extended to animal husbandry, dairy, and fisheries in 2018-19",
                "Credit limit up to ₹3 Lakh at benchmark 7% simple interest",
                "Interest Subvention Scheme (ISS): 1.5% subvention to lending institutions + 3% Prompt Repayment Incentive (PRI) to farmers, resulting in net 4% effective interest rate"
            ],
            "validity": "Card valid for 5 years subject to annual review",
            "exam_relevance": "Extremely High. R. V. Gupta committee, ₹3 Lakh limit, net 4% interest with prompt repayment."
        },
        {
            "name": "PM Surya Ghar: Muft Bijli Yojana",
            "nodal_ministry": "Ministry of New and Renewable Energy (MNRE)",
            "launch_date": "February 2024",
            "total_outlay": "₹75,021 Crore",
            "target": "1 Crore residential households to install rooftop solar units",
            "benefit": "Up to 300 units of free electricity every month",
            "subsidy_structure": "₹30,000 for 1 kW system; ₹60,000 for 2 kW system; ₹78,000 for 3 kW or larger systems",
            "financing": "Concessional collateral-free bank loans up to ₹2 Lakh at around 7% interest rate through national portal",
            "exam_relevance": "Top Priority Current Scheme. ₹75,021 Cr outlay, 1 Cr households, 300 units free."
        },
        {
            "name": "PM Vishwakarma Yojana",
            "nodal_ministry": "Ministry of Micro, Small and Medium Enterprises (MSME)",
            "launch_date": "17 September 2023 (Vishwakarma Jayanti)",
            "total_outlay": "₹13,000 Crore",
            "target_beneficiaries": "Traditional artisans and craftspeople working with hands and tools across 18 traditional trades (e.g. Carpenter, Blacksmith, Potter, Cobbler, Tailor, Sculptor)",
            "financial_support": [
                "Collateral-free enterprise development loan: First tranche up to ₹1,00,000 (18 months repayment); Second tranche up to ₹2,00,000 (30 months repayment)",
                "Concessional interest rate of 5% with interest subvention cap of 8% by Government",
                "Skill training stipend of ₹500/day during basic & advanced training",
                "Tool-kit incentive of ₹15,000 e-voucher"
            ],
            "exam_relevance": "Very High. Outlay ₹13,000 Cr, 18 trades, ₹1L + ₹2L loan tranches at 5% interest."
        },
        {
            "name": "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
            "nodal_ministry": "Ministry of Housing and Urban Affairs (MoHUA)",
            "launch_date": "1 June 2020",
            "implementation_partner": "Small Industries Development Bank of India (SIDBI)",
            "target": "Urban, peri-urban, and rural street vendors vending before 24 March 2020",
            "tranches": "First Tranche: Collateral-free working capital loan up to ₹10,000 (1 year); Second Tranche: Up to ₹20,000 (on timely repayment); Third Tranche: Up to ₹50,000",
            "incentive": "7% interest subsidy credited directly to bank account on timely repayment; cashback up to ₹1,200/year on digital transactions",
            "exam_relevance": "High. Loan amounts ₹10k, ₹20k, ₹50k; 7% interest subsidy; SIDBI implementation."
        },
        {
            "name": "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)",
            "nodal_agency": "National Health Authority (NHA), Ministry of Health and Family Welfare",
            "launch_date": "23 September 2018 (Ranchi, Jharkhand)",
            "health_cover": "₹5,00,000 per family per year for secondary and tertiary healthcare hospitalization",
            "target_beneficiaries": "Bottom 40% vulnerable families identified based on SECC 2011 data (now expanded to include all senior citizens aged 70+ regardless of income)",
            "features": "Cashless and paperless access at public and empaneled private hospitals nationwide. Covers 3 days pre-hospitalization and 15 days post-hospitalization.",
            "exam_relevance": "Very High. ₹5 Lakh cover, NHA implementation, expansion to all citizens 70+."
        },
        {
            "name": "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
            "nodal_ministry": "Ministry of Rural Development",
            "launch_date": "20 November 2016 (restructured from Indira Awaas Yojana)",
            "unit_cost_assistance": "₹1,20,000 in plain areas; ₹1,30,000 in hilly, difficult, and IAP districts",
            "minimum_size": "25 sq. meters including a dedicated cooking area",
            "cost_sharing": "60:40 between Centre and States in plain areas; 90:10 for North Eastern and Himalayan States",
            "exam_relevance": "High. Assistance ₹1.2 Lakh (plains) / ₹1.3 Lakh (hills), 60:40 sharing."
        },
        {
            "name": "Jal Jeevan Mission (JJM) - Har Ghar Jal",
            "nodal_ministry": "Ministry of Jal Shakti (Department of Drinking Water and Sanitation)",
            "launch_date": "15 August 2019",
            "objective": "Provide Functional Household Tap Connection (FHTC) to every rural household with supply of 55 litres of water per capita per day (lpcd) of prescribed quality on regular basis",
            "first_certified_state": "Goa became India's first 'Har Ghar Jal' certified state; Dadra & Nagar Haveli and Daman & Diu first certified UT; Burhanpur (MP) first certified district",
            "exam_relevance": "High. 55 lpcd water quantity, Goa first certified state, Burhanpur first district."
        }
    ]
}

with open(os.path.join("public", "data", "schemes", "government-schemes.json"), "w", encoding="utf-8") as f:
    json.dump(schemes_data, f, indent=2, ensure_ascii=False)

# 3. REPORTS AND INDEXES
reports_data = {
    "title": "Master Directory of Global and National Reports, Indexes, and Rankings",
    "total_indexes": 22,
    "last_updated": "2026-09-13",
    "indexes": [
        {
            "index_name": "Human Development Index (HDI)",
            "publishing_organization": "United Nations Development Programme (UNDP)",
            "dimensions": "1. Long and healthy life (Life expectancy at birth), 2. Knowledge (Expected years of schooling & Mean years of schooling), 3. Decent standard of living (GNI per capita in PPP $)",
            "india_rank_latest": "134 (Score 0.644 - Medium Human Development category)",
            "top_ranking_country": "Switzerland",
            "key_fact": "Conceptualized in 1990 by Pakistani economist Mahbub ul Haq and Indian Nobel laureate Amartya Sen."
        },
        {
            "index_name": "Global Gender Gap Report",
            "publishing_organization": "World Economic Forum (WEF)",
            "dimensions": "Economic Participation and Opportunity, Educational Attainment, Health and Survival, Political Empowerment",
            "india_rank_latest": "129 out of 146 countries",
            "top_ranking_country": "Iceland (Ranked #1 for 15 consecutive years)",
            "key_fact": "Assesses gender parity. Global score indicates it will take over a century to achieve full parity."
        },
        {
            "index_name": "Global Hunger Index (GHI)",
            "publishing_organization": "Concern Worldwide (Ireland) and Welthungerhilfe (Germany)",
            "indicators": "1. Undernourishment (1/3 weight), 2. Child Stunting (1/6 weight), 3. Child Wasting (1/6 weight), 4. Child Mortality (1/3 weight)",
            "india_rank_latest": "105 out of 127 countries (Level: Serious)",
            "top_ranking_country": "Belarus, Bosnia & Herzegovina, Chile (among lowest hunger group)",
            "key_fact": "India categorizes in the 'Serious' hunger severity band with score ~27.3."
        },
        {
            "index_name": "Global Innovation Index (GII)",
            "publishing_organization": "World Intellectual Property Organization (WIPO)",
            "dimensions": "Innovation Inputs (Institutions, Human capital, Infrastructure, Market sophistication, Business sophistication) and Innovation Outputs (Knowledge & tech outputs, Creative outputs)",
            "india_rank_latest": "39 out of 133 economies",
            "top_ranking_country": "Switzerland (#1 for 14th consecutive year), followed by Sweden and USA",
            "key_fact": "India jumped from 81st position in 2015 to top 40 in 2024-2026, leading lower-middle income economies."
        },
        {
            "index_name": "World Press Freedom Index",
            "publishing_organization": "Reporters Without Borders (Reporters Sans Frontieres - RSF, Paris)",
            "indicators": "Political context, Legal framework, Economic context, Sociocultural context, Safety of journalists",
            "india_rank_latest": "159 out of 180 countries",
            "top_ranking_country": "Norway (#1), Denmark (#2), Sweden (#3)",
            "key_fact": "Norway has retained the top position for 8 consecutive years."
        },
        {
            "index_name": "World Happiness Report",
            "publishing_organization": "UN Sustainable Development Solutions Network (SDSN)",
            "variables": "GDP per capita, Social support, Healthy life expectancy, Freedom to make life choices, Generosity, Perceptions of corruption",
            "india_rank_latest": "126 out of 143 countries",
            "top_ranking_country": "Finland (#1 for 7th consecutive year), followed by Denmark and Iceland",
            "key_fact": "Published annually on International Day of Happiness (20th March)."
        },
        {
            "index_name": "Corruption Perceptions Index (CPI)",
            "publishing_organization": "Transparency International (Berlin, Germany)",
            "scale": "0 (Highly Corrupt) to 100 (Very Clean)",
            "india_rank_latest": "93 out of 180 countries (Score: 39)",
            "top_ranking_country": "Denmark (Score: 90 - Least Corrupt)",
            "key_fact": "Assesses perceived levels of public sector corruption based on 13 data sources."
        },
        {
            "index_name": "Logistics Performance Index (LPI)",
            "publishing_organization": "World Bank",
            "dimensions": "Customs clearance efficiency, Quality of trade & transport infrastructure, Ease of arranging competitively priced shipments, Competence of logistics services, Tracking & tracing, Timeliness",
            "india_rank_latest": "38 out of 139 countries",
            "top_ranking_country": "Singapore (#1), Finland (#2)",
            "key_fact": "India's rank improved from 54th (2014) to 38th supported by PM Gati Shakti and National Logistics Policy."
        },
        {
            "index_name": "Henley Passport Index",
            "publishing_organization": "Henley & Partners (based on official data from IATA)",
            "india_rank_latest": "82 (Visa-free or visa-on-arrival access to 58 destinations)",
            "top_ranking_country": "Singapore (#1 with visa-free access to 195 destinations)",
            "key_fact": "Ranks world's passports according to the number of destinations holders can access without prior visa."
        },
        {
            "index_name": "National Multidimensional Poverty Index (MPI) - India",
            "publishing_organization": "NITI Aayog (using NFHS-5 microdata)",
            "dimensions": "Health (Nutrition, Child & Adolescent mortality, Maternal health), Education (Years of schooling, School attendance), Standard of Living (Cooking fuel, Sanitation, Drinking water, Electricity, Housing, Assets, Bank Account)",
            "key_findings": "Multidimensional poverty in India declined from 29.17% (2013-14) to 11.28% (2022-23); 24.82 crore people exited multidimensional poverty. Uttar Pradesh, Bihar, and Madhya Pradesh registered fastest reductions.",
            "top_performing_state": "Kerala has the lowest proportion of multidimensionally poor citizens (0.55%)."
        },
        {
            "index_name": "State Energy and Climate Index (SECI)",
            "publishing_organization": "NITI Aayog",
            "top_performing_states": "Larger States: 1. Gujarat, 2. Kerala, 3. Punjab. Smaller States: Goa. UTs: Chandigarh.",
            "key_parameters": "DISCOM performance, Clean energy initiatives, Energy efficiency, Environmental sustainability"
        },
        {
            "index_name": "State Food Safety Index (SFSI)",
            "publishing_organization": "Food Safety and Standards Authority of India (FSSAI)",
            "top_performing_states": "Larger States: Kerala (#1), Punjab (#2), Tamil Nadu (#3). Smaller States: Goa (#1). UTs: Jammu & Kashmir (#1).",
            "key_fact": "Announced annually on World Food Safety Day (7th June)."
        }
    ]
}

with open(os.path.join("public", "data", "reports", "reports-and-indexes.json"), "w", encoding="utf-8") as f:
    json.dump(reports_data, f, indent=2, ensure_ascii=False)

# 4. APPOINTMENTS, AWARDS & SPORTS
appointments_data = {
    "title": "Master Directory of High-Yield Appointments, National & International Awards, and Sports",
    "version": "2026.09",
    "constitutional_and_regulatory_heads": [
        {"position": "President of India", "incumbent": "Droupadi Murmu", "details": "15th President of India; First tribal woman President and youngest person to assume the office; former Governor of Jharkhand."},
        {"position": "Vice-President of India & Chairman of Rajya Sabha", "incumbent": "Jagdeep Dhankhar", "details": "14th Vice-President of India; former Governor of West Bengal."},
        {"position": "Chief Justice of India (CJI)", "incumbent": "Justice Sanjiv Khanna", "details": "51st Chief Justice of India (succeeded Justice D.Y. Chandrachud); term up to May 2025."},
        {"position": "Speaker of Lok Sabha", "incumbent": "Om Birla", "details": "Re-elected Speaker of the 18th Lok Sabha (represents Kota, Rajasthan)."},
        {"position": "Chief Election Commissioner (CEC)", "incumbent": "Rajiv Kumar", "details": "25th CEC; conducts General Elections, Presidential elections."},
        {"position": "Comptroller and Auditor General of India (CAG)", "incumbent": "K. Sanjay Murthy", "details": "Appointed under Article 148; former Secretary of Higher Education."},
        {"position": "Attorney General for India", "incumbent": "R. Venkataramani", "details": "16th Attorney General of India appointed under Article 76."},
        {"position": "Governor, Reserve Bank of India (RBI)", "incumbent": "Shaktikanta Das", "details": "25th Governor of RBI; Central Banker of the Year global recognition."},
        {"position": "Deputy Governors of RBI (4 posts)", "incumbents": "1. Michael Debabrata Patra, 2. M. Rajeshwar Rao, 3. T. Rabi Sankar, 4. Swaminathan Janakiraman", "details": "Oversee Monetary Policy, Regulation, Fintech & Currency Management."},
        {"position": "Chairperson, Securities and Exchange Board of India (SEBI)", "incumbent": "Madhabi Puri Buch", "details": "First woman Chairperson of SEBI and first from the private sector."},
        {"position": "Chairman, Insurance Regulatory and Development Authority of India (IRDAI)", "incumbent": "Debasish Panda", "details": "HQ in Hyderabad; sets insurance penetration and solvency norms."},
        {"position": "Chairperson, Pension Fund Regulatory and Development Authority (PFRDA)", "incumbent": "Deepak Mohanty", "details": "HQ in New Delhi; regulates NPS and Atal Pension Yojana."},
        {"position": "Chairman, National Bank for Agriculture and Rural Development (NABARD)", "incumbent": "Shaji K. V.", "details": "HQ in Mumbai; apex refinancing agency for agriculture and rural credit."},
        {"position": "Chairman & Managing Director, Small Industries Development Bank of India (SIDBI)", "incumbent": "Manoj Mittal", "details": "HQ in Lucknow; implements MUDRA, SVANidhi, and MSME credit support."},
        {"position": "Managing Director, National Housing Bank (NHB)", "incumbent": "Sanjay Shukla", "details": "HQ in New Delhi; wholly owned by Government of India (divested by RBI)."},
        {"position": "Chairperson, Competition Commission of India (CCI)", "incumbent": "Ravneet Kaur", "details": "First woman regular Chairperson of CCI; prevents anti-competitive practices."},
        {"position": "Chairman, 16th Finance Commission", "incumbent": "Dr. Arvind Panagariya", "details": "Appointed under Article 280; former Vice-Chairman of NITI Aayog; Secretary: Ritvik Ranjanam Pandey."},
        {"position": "Vice-Chairperson, NITI Aayog", "incumbent": "Suman Bery", "details": "Eminent macro-economist; succeeded Dr. Rajiv Kumar."},
        {"position": "Chief Executive Officer (CEO), NITI Aayog", "incumbent": "B. V. R. Subrahmanyam", "details": "Former Commerce Secretary and Chief Secretary of Jammu & Kashmir."}
    ],
    "major_awards": [
        {
            "award": "Bharat Ratna (2024 Conferred)",
            "details": "Highest civilian award instituted in 1954. Conferred upon 5 illustrious personalities: 1. Karpoori Thakur (former Bihar CM, champion of social justice - posthumous), 2. Lal Krishna Advani (former Deputy PM), 3. P. V. Narasimha Rao (former PM who pioneered 1991 economic reforms - posthumous), 4. Chaudhary Charan Singh (former PM and champion of farmers - posthumous), 5. Dr. M. S. Swaminathan (Father of India's Green Revolution - posthumous)."
        },
        {
            "award": "Dadasaheb Phalke Award",
            "details": "India's highest award in the field of cinema presented annually at National Film Awards. Latest recipients: Waheeda Rehman (53rd recipient) and Mithun Chakraborty (54th recipient)."
        },
        {
            "award": "58th Jnanpith Award",
            "details": "India's highest literary honour presented by Bharatiya Jnanpith. Jointly conferred upon: 1. Gulzar (renowned Urdu poet and lyricist), and 2. Jagadguru Rambhadracharya (Sanskrit scholar and polyglot)."
        },
        {
            "award": "Nobel Prizes 2024",
            "recipients": [
                {"category": "Physiology or Medicine", "winners": "Victor Ambros and Gary Ruvkun", "citation": "For the discovery of microRNA and its role in post-transcriptional gene regulation."},
                {"category": "Physics", "winners": "John J. Hopfield and Geoffrey E. Hinton", "citation": "For foundational discoveries and inventions that enable machine learning with artificial neural networks."},
                {"category": "Chemistry", "winners": "David Baker (computational protein design) and Demis Hassabis & John M. Jumper (AlphaFold protein structure prediction)", "citation": "For breakthroughs in computational protein design and 3D protein structure prediction."},
                {"category": "Literature", "winners": "Han Kang (South Korea)", "citation": "For her intense poetic prose that confronts historical traumas and exposes the fragility of human life (First South Korean writer to win Nobel in Literature; author of The Vegetarian)."},
                {"category": "Peace", "winners": "Nihon Hidankyo (Japan)", "citation": "Grassroots movement of atomic bomb survivors from Hiroshima and Nagasaki (Hibakusha), for its efforts to achieve a world free of nuclear weapons."},
                {"category": "Economic Sciences (Sveriges Riksbank Prize)", "winners": "Daron Acemoglu, Simon Johnson, and James A. Robinson", "citation": "For studies of how institutions are formed and affect prosperity."}
            ]
        },
        {
            "award": "Booker Prize & International Booker Prize",
            "details": "International Booker Prize 2024 awarded to German author Jenny Erpenbeck and translator Michael Hofmann for the novel 'Kairos'. Booker Prize 2024 awarded to British author Samantha Harvey for 'Orbital' (novel set aboard the International Space Station)."
        }
    ],
    "sports_highlights": [
        {
            "event": "ICC Men's T20 World Cup 2024",
            "hosts": "USA and West Indies",
            "champion": "India (Defeated South Africa by 7 runs in the final at Kensington Oval, Barbados)",
            "key_facts": "India won its second T20 World Cup title (first was in 2007 under MS Dhoni). Captain: Rohit Sharma; Player of the Series: Jasprit Bumrah; Player of the Match in Final: Virat Kohli (76 runs). India remained undefeated throughout the tournament."
        },
        {
            "event": "Paris Olympics 2024",
            "host_city": "Paris, France (Motto: Games Wide Open)",
            "india_medals": "Total 6 Medals (1 Silver, 5 Bronze).",
            "indian_medalists": [
                "Neeraj Chopra (Silver in Men's Javelin Throw - 89.45 m; Pakistan's Arshad Nadeem won Gold with Olympic record 92.97 m)",
                "Manu Bhaker (Bronze in Women's 10m Air Pistol - First Indian woman shooter to win Olympic medal)",
                "Manu Bhaker & Sarabjot Singh (Bronze in 10m Air Pistol Mixed Team - Manu Bhaker became first Indian athlete in post-independence era to win 2 medals in a single Olympics)",
                "Swapnil Kusale (Bronze in Men's 50m Rifle 3 Positions)",
                "Indian Men's Hockey Team (Bronze medal defeating Spain 2-1; Captain: Harmanpreet Singh; PR Sreejesh retired after tournament)",
                "Aman Sehrawat (Bronze in Men's 57kg Freestyle Wrestling - Youngest Indian Olympic individual medalist at age 21)"
            ]
        },
        {
            "event": "Paris Paralympics 2024",
            "india_performance": "Historic best tally of 29 Medals (7 Gold, 9 Silver, 13 Bronze), finishing 18th in medal standings.",
            "gold_medalists": [
                "Avani Lekhara (Women's 10m Air Rifle Standing SH1 - First Indian woman with 2 Paralympic golds)",
                "Nitesh Kumar (Men's Singles SL3 Badminton)",
                "Sumit Antil (Men's Javelin Throw F64 - Paralympic record 70.59 m, consecutive gold)",
                "Harvinder Singh (Men's Individual Recurve Open Archery - India's first ever archery gold)",
                "Dharambir (Men's Club Throw F51 - Asian record)",
                "Praveen Kumar (Men's High Jump T64 - Asian record 2.08 m)",
                "Navdeep Singh (Men's Javelin Throw F41)"
            ]
        },
        {
            "event": "Grand Slam Tennis Champions (Recent)",
            "highlights": "Carlos Alcaraz won French Open and Wimbledon 2024. Jannik Sinner won Australian Open and US Open 2024. Aryna Sabalenka won Australian Open and US Open 2024. Iga Swiatek won French Open 2024. Barbora Krejcikova won Wimbledon 2024. Rohan Bopanna became oldest Grand Slam champion in Open Era winning Australian Open 2024 Men's Doubles at age 43."
        }
    ]
}

with open(os.path.join("public", "data", "appointments", "appointments-and-awards.json"), "w", encoding="utf-8") as f:
    json.dump(appointments_data, f, indent=2, ensure_ascii=False)

print("Economy, Schemes, Reports, and Appointments datasets generated successfully.")
